### ISSUE TITLE
signrequest_client/api/api_tokens_api.py has async as named argument.

### ISSUE THREAD

**Issue by shivshankardayal** [SignRequest/signrequest-python-client#4]
signrequest_client/api/api_tokens_api.py has `async` as named argument. `async` is a keyword in Python 3.

**Comment by cjackson** [comment]
Thanks @shivshankardayal for reporting this issue. I've implemented a fix in PR #5. I'll be pushing out a release shortly.

**Comment by shivshankardayal** [comment]
Thanks a lot Chris. It was a small but very important change.
